# Generated by Django 5.2.15 on 2026-07-02 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_exercise_created_by_exercise_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('consolidate', 'Consolidate'), ('push', 'Push'), ('explore', 'Explore')], max_length=12)),
                ('bpm_target', models.PositiveIntegerField()),
                ('target_accuracy', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['user', 'date'], name='goals_daily_user_id_2fde8e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'kind'), name='unique_daily_challenge_kind')],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_bpm', models.PositiveIntegerField()),
                ('target_accuracy', models.FloatField(default=0.8)),
                ('initial_target_date', models.DateField()),
                ('target_date', models.DateField()),
                ('start_effective_bpm', models.FloatField(default=0.0)),
                ('best_effective_bpm', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'target_date', 'id'],
                'indexes': [models.Index(fields=['user', 'status'], name='goals_objec_user_id_f76d3f_idx')],
            },
        ),
    ]
