# Generated by Django 5.2.15 on 2026-07-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm_target', models.PositiveIntegerField()),
                ('timing_accuracy', models.FloatField()),
                ('pitch_accuracy', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('bpm_achieved', models.FloatField()),
                ('score', models.FloatField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='attempts/%Y/%m/')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'exercise', '-created_at'], name='practice_pr_user_id_1e66e5_idx'), models.Index(fields=['exercise', 'bpm_target', 'verified', '-score'], name='practice_pr_exercis_91b00e_idx')],
            },
        ),
    ]
